# Generated by Django 4.0.4 on 2022-05-12 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
