# Generated by Django 4.0.4 on 2022-05-12 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blog_post_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='descricao',
            field=models.CharField(max_length=2000),
        ),
    ]
