# Generated by Django 4.0.4 on 2022-05-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_blog_post_img_alter_blog_post_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='img',
            new_name='image',
        ),
    ]
