# Generated by Django 4.0.4 on 2022-05-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_cadeira_linguagem_professor_projeto_delete_tarefa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadeira',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Linguagem',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='Projeto',
            new_name='Project',
        ),
    ]
