# Generated by Django 4.0.4 on 2022-05-17 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_cadeira_class_rename_linguagem_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='ects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
