# Generated by Django 4.0.4 on 2022-05-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_hobbie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbie',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
