# Generated by Django 4.0.4 on 2022-05-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_hobbie_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_0', models.IntegerField(default=0)),
                ('question_1', models.CharField(max_length=20)),
                ('question_2', models.CharField(max_length=20)),
                ('question_3', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
