# Generated by Django 4.0.4 on 2022-05-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetc_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_topics',
            field=models.ManyToManyField(to='portfolio.projetc_topic'),
        ),
    ]
