# Generated by Django 4.0.4 on 2022-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_web_techniques'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('authors', models.TextField(max_length=500)),
                ('teacher', models.TextField(max_length=500)),
                ('year', models.IntegerField(default=2019)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
